<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="p.bmp" />
    <None Remove="p1.bmp" />
    <None Remove="p2.bmp" />
    <None Remove="p3.bmp" />
    <None Remove="p4.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="p.bmp">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
